### ISSUE TITLE
Doesn't work with expo-cli

### ISSUE THREAD

**Issue by syropian** [GeekyAnts/vue-native-core#103]
CRNA is deprecated in favour of expo-cli. I tried getting setup manually by installing, `vue-native-core`, `vue-native-helper`, and `vue-native-scripts`. I added the suggested `vueTransformerPlugin.js` file, created a `rn-cli.config.js` file in the root, and added it to my `app.json` file:

```
{
  ...
  "rnCliPath": "./rn-cli.config.js"
}
```

When running `npm start` I simply get: `Metro Bundler process exited with code 0`.

**Comment by marvinrabe** [comment]
Your docs https://vue-native.io/docs/installation.html mention React Native CLI. But when I click on the link, this page opens: https://facebook.github.io/react-native/docs/getting-started.html There is a getting started guide using expo-cli.

So I installed expo-cli like described and continued with the vue-native-cli setup.

On calling 

    npm install -g vue-native-clivue-native init <projectName>

I get this error:

> Please globally install create-react-native-app dependency.

Which is not really a surprise because I diddnt install crna. And I dont want to because its deprecated. And I am rather thinking about using NativeScript with Vue instead. At this point Vue Native CLI looks quite abandoned to me.

Are you planning to update to expo-cli?

**Comment by neeraj-singh47** [comment]
@marvinrabe We are working on it. We'll update the vue-native cli soon

**Comment by EricBrandt2512** [comment]
Is there a workaround to get this started? I love Vue and switching to react would be a bummer

**Comment by marvinrabe** [comment]
@EricBrandt2512 Maybe consider using https://www.nativescript.org/vue . That one is better maintained.

**Comment by neeraj-singh47** [comment]
CRNA has been deprecated in favour of expo-cli. The latest version of vue-native-cli does not depend CRNA anymore.
