### ISSUE TITLE
Add compatibility for hot reload

### ISSUE THREAD

**Issue by terrydemco** [GeekyAnts/vue-native-core#133]
Fresh install. 
Hot reloading does not work with .vue files, .js files do work however. 
Live reloading seems to work just fine with vue files.

**Comment by apolokaklab** [comment]
Mee to

**Comment by ridvanaltun** [comment]
I have the same problem too. Is this normal?

**Comment by icarter09** [comment]
@ridvanaltun does this happen every time for .vue files?

**Comment by terrydemco** [comment]
Yes

**Comment by icarter09** [comment]
@terrydemco I believe I'm seeing this as well. Is this an issue or how it's supposed to function? I feel like this is intended functionality.

**Comment by terrydemco** [comment]
It doesn’t happen in react native, only vue native, it is not the intended functionality. Fire up react native and check it out.

**Comment by icarter09** [comment]
@terrydemco I'll fire up a react native project tomorrow and will check it out. Thanks for the heads up.

**Comment by RishabhKarnad** [comment]
In Vue Native, all modules (whether JS or Vue) are loaded by Metro after certain transformations are applied. The transformations include stuff that allows HMR to work. In the default configuration, this is done in the `vueTransformPlugin.js` file, which uses different transformers for different file types.

JS files use `metro-react-native-babel-transformer` which is configured for HMR. `vue-native-scripts` needs to be modified for this, so that hot reloading would work with `.vue` files.

I am looking into this.

**Comment by Skyhark-Projects** [comment]
Any updates ? We need to rebuild everything on each change, so it's slows down dramatically development time

**Comment by RishabhKarnad** [comment]
Upgrading to React Native 0.61+ will enable Fast Refresh, which is compatible with Vue Native.

Due to this, we are no longer looking into support for the hot reload mechanism used by RN 0.60 and older. Since we will be slowly phasing out support for older RN versions anyway, it would be best to upgrade to 0.61 or higher.

Please open new issues on this repo in case of specific issues with Fast Refresh.
