### ISSUE TITLE
Export project to pure React Native

### ISSUE THREAD

**Issue by tmaly1980** [GeekyAnts/vue-native-core#172]
Is there a way to convert a .vue file component into the React Native .js version, and save that on disk? I'd love to use this framework but am concerned if it eventually loses support then I'm stuck rewriting all my vue components by hand into react native equivalents. I'd love some sort of script that can do that for me (ie convert the whole project back to RN only code).

**Comment by icarter09** [comment]
@tmaly1980 this is a great idea. I'm wondering if this should just be created as a completely separate project/script.

**Comment by RishabhKarnad** [comment]
@tmaly1980 `vue-native-scripts` can be used to transpile Vue SFCs, but the React Native code generated is not exactly human readable (it contains many indirections and optimisations), and only really acts as a wrapper around a Vue object, so that  it may run in React Native's runtime.

Also, the underlying ideas of Vue and React are quite different and translating one into the other, in such a way that it would be both consistent with React's values and maintainable at the same time is quite a different challenge than allowing one library to run inside the runtime of another, which is relatively simple. It would probably be cleaner to rewrite an app.

It's an interesting idea, but as @icarter09 said, it would probably be better maintained as a separate project.

For now, you don't need to worry about losing support since Vue Native is under development once more 😄

**Comment by Azghour-Saad** [comment]
Hi @RishabhKarnad  ,

Please, is there a way to convert a .vue file component into the React Native online **( Like : https://tools.w3cub.com/vue-to-react )** OR another package  unlike this one ` vue-native-scripts`
