### ISSUE TITLE
"Unable to resolve "../../App" from "node_modules\expo\AppEntry.js""

### ISSUE THREAD

**Issue by rowanfuchs** [GeekyAnts/vue-native-core#194]
This issue remains after a regular Vue installation where i followed the docs

**Comment by anoop-ananthan** [comment]
@rowanfuchs please try after updating vue-native
```
npm install -g vue-native-cli
```
Works fine for me. They have fixed it.

**Comment by RishabhKarnad** [comment]
@rowanfuchs @anoop-ananthan It hasn't exactly been fixed. The issue is caused by newer versions of Expo, which ignores the `sourceExts` in `metro.config.js`. You'll need to add `sourceExts` with the `vue` extension in `app.json` of your newly generated project as mentioned in #183 

We still haven't been able to update the documentation about this since we've been a little tied up. You are welcome to raise a PR in https://github.com/GeekyAnts/vue-native-website if you are able

This issue is a duplicate, but I'll keep it open until either
- The docs can be updated (and maybe even the CLI modified to make this change automatically)
- Expo is fixed

**Comment by s3bul** [comment]
I have this problem a few days ago, but after i add
```json
    "packagerOpts": {
      "sourceExts": [ "js", "json", "ts", "tsx", "jsx", "vue"],
      "config": "metro.config.js"
    }
```
to app.json file, the problem has been solved.

**Comment by RishabhKarnad** [comment]
This should no longer happen for freshly created projects with `vue-native-cli@0.1.1`

**Comment by RishabhKarnad** [comment]
@rowanfuchs The documentation will be updated this week

**Comment by sumukhah** [comment]
try downloading without yarn
