### ISSUE TITLE
null is not an object (evaluating 'RNGestureHandlerModule.default.Direction')

### ISSUE THREAD

**Issue by Arwantys** [GeekyAnts/vue-native-core#206]
Hello,

I wanted to transfer my project native view with expo on a project native view without expo and I now have an error, from what I read it should be used Pod, but there is no podfile in the ios files added by native view.

Here is the error https://prnt.sc/p61v3c

Thank !

**Comment by RishabhKarnad** [comment]
@Arwantys Could you please share some more code? It would be great if you could create a small repo that reproduces the issue and share it here.

**Comment by Arwantys** [comment]
@RishabhKarnad Just vue-native init <projectName> --no-expo and Vue Native Router (https://vue-native.io/docs/vue-native-router.html) installed

**Comment by RishabhKarnad** [comment]
Have you installed the peer deps required by `vue-native-router`?

>NOTE
>
>Some of its dependencies assume that the following packages are already installed:
>
> • react-native-reanimated
> • react-native-gesture-handler
> • react-native-paper

**Comment by Arwantys** [comment]
Yes, it's installed, but not working

**Comment by RishabhKarnad** [comment]
If you are using React Native 0.59, you will need to separately link those dependencies as described here: https://reactnavigation.org/docs/en/getting-started.html#installation

I didn't mention earlier, but you may also need to run
```
pod init
```
since you said there is no podfile.

If this has already been done, or if you are using React Native 0.60, please do one of the following to help me understand the issue:
- create a repo which reproduces the issue and share it here
- share the `package.json`

**Comment by Arwantys** [comment]
It is resolved, I went directly by the installation of React and not of sight and everything was niquel, thank you!
