### ISSUE TITLE
vue-native in react-native-cli drawer navigation not working

### ISSUE THREAD

**Issue by pesaregorg** [GeekyAnts/vue-native-core#213]
https://github.com/pesaregorg/simple-vue-native
this is my  project
but not working drawer navigation
where is the problem?
..........
i tested tab navigation and it was no problem.

**Comment by RishabhKarnad** [comment]
@pesaregorg It would have been better if this issue was raised in the [Vue Native Router repository](https://github.com/GeekyAnts/vue-native-router/issues)

Your code seems to be working fine. The drawer slides out with the swipe gesture from the left side of the screen. If you need a button in the header, you will have to add that yourself in the template.
