### ISSUE TITLE
Flat-List Infinite Loop Warning

### ISSUE THREAD

**Issue by jonnycraze** [GeekyAnts/vue-native-core#220]
**Description of the bug**
When using the flat list with an array, regardless of whether i use the render-prop-fn or use the renderItem prop directly I receive a warning about a potential infinite loop. I've reverted as far back as the example in the website documentation and continue to receive the error.

The following code is where I'm getting the error:
```
<template>
  <view class="dashboard">
    <view class="button-bar">
      <button :on-press="toggleView('overview')" title="Overview" />
      <button :on-press="toggleView('logs')" title="Logs" />
      <!-- <button :on-press="toggleView('map')">Map</button> -->
      <text>{{showOverview}}</text>
    </view>
    <view class="overview" v-if="showOverview">
      <text>Welcome, {{user.username}}</text>
    </view>
    <view class="logs" v-if="showLogs">
      <text>logs:</text>
      <flat-list :data="logs" :keyExtractor="(item, index) => index.toString()">
        <view render-prop-fn="renderItem" >
          <text>{{args.item.type}}</text>
        </view>
      </flat-list>
    </view>
  </view>
</template>
```

**To Reproduce**
1. Use flat-list in template
2. Pass an array of objects

**What I expected**
I Expect no errors when following the documentation

**Screenshots**

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes

**Development platform (please complete the following information):**
 - OS: Windows
 - Shell/terminal: VScode

**The device on which I run my Vue Native app**
 - Device: Samsung Galaxy s8
 - OS: Android 9

**Additional context**

**Comment by RishabhKarnad** [comment]
Edited previous comment for better code formatting.

**Comment by RishabhKarnad** [comment]
@jonnycraze a more complete code example could help here, but it seems the problem might be caused by the event handlers you have provided, like `:on-press`.

Vue Native has a limitation that all handlers provided need to be callbacks. This means that the shorthand notation of just the function call used frequently in Vue.js doesn't work with Vue Native.

Try replacing them with something like `:on-press="() => toggleView('overview')"`

We'll ensure that this is conveyed more clearly in the docs.

Let us know here if this solves the problem.

**Comment by jonnycraze** [comment]
Thanks so much, this did resolve the problem, thank you, and thank you for updating the docs to reflect it.
