### ISSUE TITLE
Question: vue-native with vuetify

### ISSUE THREAD

**Issue by yanbert** [GeekyAnts/vue-native-core#222]
Hi,
i use vuetify for my project and i want to build native app using vue native. i look for document to do that could you help me how can i setup vue native and vuetify together

thank you

**Comment by RishabhKarnad** [comment]
Hi @yanbert. Vuetify is a web UI framework and sadly, cannot be used with Vue Native.

You can use any UI framework targeted at React Native, when writing apps with Vue Native. Since you are using Material design, I could recommend:

- [React Native Paper](https://callstack.github.io/react-native-paper/)
- [React Native Material UI](https://github.com/xotahal/react-native-material-ui)
- [React Native Material Kit](https://github.com/xinthink/react-native-material-kit)

[NativeBase](https://docs.nativebase.io/) also has Material theming options and good support for Vue Native.
