### ISSUE TITLE
Question: Bridge for native android / objective-c api's in vue-native

### ISSUE THREAD

**Issue by ashbeats** [GeekyAnts/vue-native-core#227]
Hi, 

I've been trying to figure out how to access native android / objective-c api's in vue-native. 

Could someone point me to the correct place in the docs. 

Thanks

**Comment by RishabhKarnad** [comment]
Hey @ashbeats, here are the React Native docs resources that talk about integrating native modules

iOS: https://facebook.github.io/react-native/docs/native-modules-ios
Android: https://facebook.github.io/react-native/docs/native-modules-android

Since Vue Native is based on React Native, you'll need to follow the same principles to bridge native modules with Vue Native
