### ISSUE TITLE
Question: html5 audio or JS new audio doesn't seems to work, how can to use it or make it work?

### ISSUE THREAD

**Issue by alexrok21** [GeekyAnts/vue-native-core#276]

**Comment by RishabhKarnad** [comment]
HTML5 APIs don't work in React Native and Vue Native. You will either need to make a WebView to load HTML into the native app or use a library to play audio in the app

WebView
https://github.com/react-native-community/react-native-webview
Usage in Vue Native (needs to be imported and added to components in the <script> part)
https://vue-native.io/docs/basic-components.html#WebView

Third party libraries that use native components instead of HTML5 audio APIs
https://www.npmjs.com/package/react-native-track-player
https://www.npmjs.com/package/react-native-sound-player

**Comment by alexrok21** [comment]
thanks!
