### ISSUE TITLE
Unrecognized font family 'ionicons'

### ISSUE THREAD

**Issue by OsamaMohammed** [GeekyAnts/vue-native-core#292]
**Description of the bug**
In a newly initialized vue-native project, icons doesn't work and fires the error

  `Unrecognized font family 'ionicons'`

Things I've tried so far...

- Initialize new project the latest versions
- downgrade expo
- installing react-native-vector-icons
- tried installing react-native and execute react-native link react-native-vector-icons
- Forcing Font.loadAsync to load the fonts from "@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts" or from "native-base/Fonts"
- removed package-lock, node_modules, expo client and reinstalled them, and started the project with `expo start -c`

**To Reproduce**

`vue-native init vueNativeTest`

and use the below simple code

```vue
<template>
    <view class="container">
        <text class="text-color-primary">My Vue Native App</text>
        <Ionicons name="md-checkmark-circle" :size="50" />
    </view>
</template>

<script>
import Vue from "vue-native-core";
import { Ionicons, FontAwesome } from "@expo/vector-icons";

export default {
    components: {
        FontAwesome,
        Ionicons,
    },
    methods: {},
    created() {},
};
</script>

<style>
.container {
    background-color: white;
    align-items: center;
    justify-content: center;
    flex: 1;
}
.text-color-primary {
    color: blue;
}
.cRed {
    color: red;
}
</style>
```

**What I expected**
Icon to appear

**Screenshots**
https://imgur.com/a/NWpV89i

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes

**Development platform (please complete the following information):**
 - OS: Windows 10
 - Shell/terminal: cmd

**The device on which I run my Vue Native app**
 - Device: iPhone 7 & Samsung A01
 - OS: iOS 13.5 and Android 10
 Expo Client latest version on time of writing

**Additional context**
```json
{
    "@expo/vector-icons": "^12.0.2",
    "expo": "~40.0.0",
    "expo-font": "^8.4.0",
    "expo-status-bar": "~1.0.3",
    "native-base": "^2.13.15",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^7.1.0",
    "react-native-web": "~0.13.12",
    "vue-native-core": "^0.2.0",
    "vue-native-helper": "^0.2.0"
}
```

**Comment by RishabhKarnad** [comment]
Where does the code snippet live in the directory structure? Is it in App.vue?

**Comment by OsamaMohammed** [comment]
> Where does the code snippet live in the directory structure? Is it in App.vue?
> 
> I'm not sure if it's a Windows thing, but could you try running it from WSL?

Its in App.vue and I was not able to run it from WSL, maybe I will try through linux later

**Comment by leonzuendel** [comment]
this is still an issue and i tried EVERY step from EVERY issue i found on several plattforms (not only git and even for only expo or react native) - it is still relevant and the documentation is literally useless and has so many errors that it's not even fun anymore...

icons are not showing due to the font family being unrecognized and loading them 1:1 like in the docs and i also tried several other ways - there not working alone and not in the (also so terribly bad documented) tab navigation

i never write issues myself but THIS drives me crazy. even a simple thing like that can't be documented right? seems like i'm giving up vue native at this point

**Comment by leonzuendel** [comment]
and btw i dont understand why all the relevant issues here are keep getting closed or ignored for months all the time (like for example the fact that expo web is not working - which makes half of this useless anyways)

**Comment by michug** [comment]
I'am also unable to make the icons works. Anyone had any luck?

**Comment by RishabhKarnad** [comment]
@OsamaMohammed @michug sorry for taking so long to reply. The Vue Native KitchenSink app has an example and uses a workaround for this issue

https://github.com/GeekyAnts/KitchenSink-Vue-Native/blob/master/src/boot/setup.vue

The workaround is to basically use a relative path to node_modules inside the `require`, instead of using the absolute path. The fonts are loaded here in advance.

Let me know if this works for you.

**Comment by michug** [comment]
> @OsamaMohammed @michug sorry for taking so long to reply. The Vue Native KitchenSink app has an example and uses a workaround for this issue
> 
> https://github.com/GeekyAnts/KitchenSink-Vue-Native/blob/master/src/boot/setup.vue
> 
> The workaround is to basically use a relative path to node_modules inside the `require`, instead of using the absolute path. The fonts are loaded here in advance.
> 
> Let me know if this works for you.

Didnt work for me

**Comment by mahimranjan** [comment]
Running into the same issue. I have been struggling with this for the last 4 days. Tried everything. Downgrade/delete/recreate. No luck. Icons are not showing and "Unrecognized font family 'ionicons'" keeps popping up.

Any updates?

**Comment by michug** [comment]
@mahimranjan  I couldn't, I cloned the kitchensink repo [(),](https://github.com/GeekyAnts/KitchenSink-Vue-Native) and after some upgrades made it work locally, copied the same setup as that app but it doesn't work for me, I cant pinpoint what is what makes it work for them. Maybe you'll have better luck

**Comment by mahimranjan** [comment]
I can't even get the repo to work.

"Error: Asset not found: {****}/KitchenSink-Vue-Native/assets/App_Icon_4_No_Transparency.png for platform:"

@RishabhKarnad  Are you guys still supporting vue-native?

**Comment by RishabhKarnad** [comment]
This seems to be an issue with Expo.
https://github.com/expo/expo/issues/11333

This issue mentions it happens on SDK 40. I can't confirm right now if it happens with older SDKs.

**Comment by mahimranjan** [comment]
@RishabhKarnad Any luck with SDK 40?

**Comment by RishabhKarnad** [comment]
The [Kitchen Sink app](https://github.com/GeekyAnts/KitchenSink-Vue-Native) has been updated to Expo SDK 40 and the fix for fonts has been added
- Use react-native-svg-transformer for SVG files (changes in vueTransformerPlugin.js)
- Use @expo/metro-config in metro.config.js
- Add new sourceExts to app.json (including .svg)
- Remove .svg from assetExts in metro.config.js

**Comment by mahimranjan** [comment]
Yes that worked! Thank you!!
