### ISSUE TITLE
React native compatibility versions

### ISSUE THREAD

**Issue by octavianvoloaca-tremend** [GeekyAnts/vue-native-core#298]
Two quick questions:

1. Which is the last version of react-native compatible with vue-native 0.1.4 and also the last for 0.2.0?

2. We have an app with more than 200 k users. I'm seeing that the project is no longer in active development. it's the time to go ahead and start porting the app in react-native?

**Comment by RishabhKarnad** [comment]
Please use the latest version of Vue Native (0.2.0). It supports RN 0.63.

Vue Native 0.1.4 also supports RN 0.63, but will throw a lot of warnings when using it.

We are trying to fix issues as quickly as possible, and are planning for another release soon. There have been delays in the past because the team has had to work on other things.
https://github.com/GeekyAnts/vue-native-core/pull/249

**Comment by octavianvoloaca-tremend** [comment]
Thank you for the answer

**Comment by ptrxwsmitt** [comment]
vue-native-cli is still creating a project with RN 0.59 with `vue-native init VN1Test --no-expo`
see https://github.com/GeekyAnts/vue-native-cli/issues/32

react-native upgrade v0.63.4 is not working on my side either :-/

RN 0.59 is only running on Node v10. That way I could get a basic app running.
Adding vue-native-router to RN 0.59 and Node v10 seems not to be working, though. I guess this is a dependency issue due to the old version.

Is there a chance https://github.com/GeekyAnts/vue-native-cli/issues/32 is getting solved soon?

**Comment by RishabhKarnad** [comment]
vue-native-cli@0.2.0 will now create a project with RN 0.63
