### ISSUE TITLE
Initializing Vue Native project with template

### ISSUE THREAD

**Issue by opeolluwa** [GeekyAnts/vue-native-core#331]
Is it possible to have option of choosing project template as we seen in likes of Ionic or React native,  adding router & navigation, especially tabbed navigation is very tasking. 

Are there pending plans for this, would like to contribute

**Comment by mawlicious** [comment]
I'm not sure if it's ok to post my own library in an issue, but here you go:
I made a library that not only actually initiates working Vue Native projects, but also gives you the option to add the Vue Native Router when initializing:

https://www.npmjs.com/package/vue-native-cli-updated

**Comment by opeolluwa** [comment]
thanks, ill check it out.

**Comment by opeolluwa** [comment]
it took a very long time to get a feedback, also, I got to know that vue-native is no longer maintained. I'll be glad to help with contributions if there are plans of getting the project up and running again. 

I hope to get a response from you soon

**Comment by mawlicious** [comment]
I don't think the actual original makers are ever gonna gonna get it back up on its feet, however, I am making a Vue Native discord server so I, or anyone else, can help others overcome the regular issues you face due to the framework being inactive, I may consider forking it and getting it back on it's feet on my own, but that'd be hard and very unlikely, anyways here's the discord: 

https://discord.gg/rPgwrD9gYa

**Comment by opeolluwa** [comment]
wow! I was thinking you're one of the backers,
since the possibility of forking is not very certain 
will you be rebuilding

**Comment by mawlicious** [comment]
I meant the possibility of having my own maintained library in general would be very uncertain 😅, its not easy to maintian open-source, but i will definitely consider maintaing a fork of this repository because its definitely worth using and such a great library.
Which is why I also made the discord so I can help other people with the problems since I've gained quite a bit of experience in this repo.

**Comment by opeolluwa** [comment]
Now I get it, I'll work around getting on the discord channel, I'm having issues with installation of the mobile application at the moment.  

In the mean time, I'll check thru vue-native source and try  grasps how it all works together. I hope to contribute too, at least to have the library up and running. It's way too promising to be depreciated 😣.

I'm Opeoluwa, BTW. Would like to know you and perhaps follow on Twitter 😅

**Comment by mawlicious** [comment]
I thino I'll be able to contact you through your discord. If you still have that problem with installing the app, just hit me up in the discord server and I'll help you as much as I could, in the meantime, kindly close this issue as I'm trying to close as many issues as possible in this library, thanks!

**Comment by mawlicious** [comment]
Also I wouldn't reccomend playing around in the source to understand how it works. The documentation is more than fine to get you started, and the problems the documentation doesn't cover you can just ask me in the discord and I'll most likely be able to answer you!
