### ISSUE TITLE
x64 support

### ISSUE THREAD

**Issue by ViRuS-CoBaS** [GeekyAnts/vue-native-core#53]
Whether in vue-native support of 64-bit libraries for android?

**Comment by neeraj-singh47** [comment]
@ViRuS-CoBaS Currently It's not supported. https://github.com/facebook/react-native/issues/2814

**Comment by mislam** [comment]
64-bit is not supported on Expo project. We need this this immediately for our Vue Native project, because Google Play Store will not receive any update from August 2019 that doesn't support 64-bit. So this is super critical.
See: https://blog.expo.io/64-bit-support-and-android-app-bundles-fe0c6a28669
